### ISSUE TITLE
TypeErrors

### ISSUE THREAD

**Issue by samp-server** [mthenw/frontail#100]
Hello,

[root@test ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@test ~]#

[root@test ~]# node -v
v8.4.0
[root@test ~]#

[root@test ~]# npm -v
5.3.0
[root@test ~]#

Any ideas why this might be happening?

[root@test ~]# frontail -n 35 -d /var/log/test &
[1] 1779
[root@test ~]# child_process.js:400
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:400:11)
    at Object.exports.spawn (child_process.js:487:38)
    at Function.module.exports.daemon (/usr/lib/node_modules/frontail/node_modules/daemon/index.js:50:31)
    at module.exports (/usr/lib/node_modules/frontail/lib/daemonize.js:52:23)
    at Object.<anonymous> (/usr/lib/node_modules/frontail/index.js:34:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

**Comment by Alpoy** [comment]
Found this: https://github.com/indexzero/daemon.node/pull/42/commits/48d0977c26fb3a6a44ae99aae3471b9d5a761085

Edit daemon/index.js and change:
-    var cwd = opt.cwd || process.cwd;
 +    var cwd = opt.cwd || process.cwd();

Works for me..

**Comment by mthenw** [comment]
@samp-server @Alpoy thanks for reporting guys!
