### ISSUE TITLE
Getting  "RangeError: Maximum call stack size exceeded" when the log file is heavy

### ISSUE THREAD

**Issue by Taymindis** [mthenw/frontail#103]
/usr/lib/node_modules/frontail/node_modules/socket.io/node_modules/engine.io/lib/socket.js:413
      this.sentCallbackFn.push.apply(this.sentCallbackFn, this.packetsFn);
                               ^

RangeError: Maximum call stack size exceeded
    at Socket.flush (/usr/lib/node_modules/frontail/node_modules/socket.io/node_modules/engine.io/lib/socket.js:413:32)
    at emitNone (events.js:72:20)
    at WebSocket.emit (events.js:166:7)
    at /usr/lib/node_modules/frontail/node_modules/socket.io/node_modules/engine.io/lib/transports/websocket.js:109:14
    at CorkedRequest.finish (_stream_writable.js:514:7)
    at afterWrite (_stream_writable.js:355:3)
    at onwrite (_stream_writable.js:346:7)
    at Socket.WritableState.onwrite (_stream_writable.js:90:5)
    at WriteWrap.afterWrite (net.js:802:12)

**Comment by mthenw** [comment]
@Taymindis thanks for reporting. what do you mean by heavy? What size is it? How many lines?

**Comment by Taymindis** [comment]
@mthenw  it is debugging the data, it logs around 100k per 100 secs

**Comment by mthenw** [comment]
Looks like it's an issue with socket.io https://github.com/socketio/socket.io/issues/1665#issuecomment-237536358

**Comment by mthenw** [comment]
@Taymindis I will release a new version in few minutes. Please let me know if it works.
