### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by hazimaqlan** [mthenw/frontail#115]
C:\Users\Servr>frontail C:\log\log.1520503819
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn tail ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by mthenw** [comment]
Hey @hazimaqlan,

looks like you are running frontail on Windows where there is no `tail` command. Right now that's the limitation.

**Comment by MDecker-MobileComputing** [comment]
I was able to run frontail on Windows 10 using the Bash shell on Ubuntu provided by the "Windows Subsystem for Linux (WSL)".

For instructions on how to install WSL you can refer to [this article](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/). 

You also need to make a separate install of Node.js in this Bash shell which can be done as follows (see also [here](https://medium.com/hackernoon/running-nodejs-on-linux-on-windows-88bd12993bae)):
````
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
````
