### ISSUE TITLE
Help required change port from 9001 to 9009

### ISSUE THREAD

**Issue by sujitrp** [mthenw/frontail#198]
I know this is a basic question but how can I change the port for frontail ?
on of my docker is using 9001 so I am getting following error. 
Solution I can think is change frontail port

`pi@raspberrypi:~ $ frontail /var/log/syslog
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:9001
    at Server.setupListenHandle [as _listen2] (net.js:1277:14)
    at listenInCluster (net.js:1325:12)
    at doListen (net.js:1458:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1304:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
`

**Comment by mthenw** [comment]
`  -p, --port <port>             listening port, default 9001`
