### ISSUE TITLE
Highlighting issues

### ISSUE THREAD

**Issue by kidac** [mthenw/frontail#228]
We are using the linux binary 4.9.1
Command line: ./frontail-linux -p 8443 /opt/server.log --ui-highlight-preset /opt/preset
But no highlighting occurs and no error message is thrown. Any hints where to start some diagnostics?

**Comment by Llibyddap** [comment]
Linux with version 4.9.1

I've actually run into this issue as well...  I have two instances of `/frontail` running.  One in a single node RancherOS cluster which works exactly as expected with the `--ui-highlight-preset` and the other running on a three node K3s cluster which doesn't deploy the highlighting.  Within the K3s environment there are no errors thrown and all the mount points, paths and files seem to work just fine.

One added item - which may or may not be related - but if I pass the `--ui-highlight` flag on creating the pod/deployment it throws this error:

```
bill@k3smaster01:~/payload/home$ kubectl logs pod/frontail-5798bcd5cb-6q6c4 -n home
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/frontail/index.js:119:30)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/frontail/bin/frontail:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

But if I deploy without the flag and then `apply` the change it doesn't through the error (but it also doesn't change the highlighting.

**Comment by Llibyddap** [comment]
An update...  I did a complete new install, including the persistent storage that the logs attached to.  Although I still am not exactly sure what caused my issue, this reinstall from scratch made everything work as advertised.
