### ISSUE TITLE
Launching frontail with uwsgi emperor

### ISSUE THREAD

**Issue by swasher** [mthenw/frontail#52]
I'm trying launch frontail with uwsgi emperor. Vassal ini contain string 

     attach-daemon = frontail /home/vagrant/log/uwsgi-error.log

or

    attach-daemon = /usr/bin/nodejs /usr/local/lib/node_modules/frontail/index.js /home/vagrant/log/uwsgi-error.log

with following error in uwsgi log (no matter which string):

    [uwsgi-daemons] respawning "/usr/bin/nodejs /usr/local/lib/node_modules/frontail/index.js /home/vagrant/log/uwsgi-error.log" (uid: 1000 gid: 1000)
    Error: Implement me. Unknown stream file type!
        at createWritableStdioStream (node.js:597:15)
        at process.stderr (node.js:628:16)
        at Object.<anonymous> (/usr/local/lib/node_modules/frontail/node_modules/connect/node_modules/debug/node.js:37:32)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous>   (/usr/local/lib/node_modules/frontail/node_modules/connect/lib/proto.js:14:13)

When I run frontail from command line, all working ok.

How to do it in right way?

**Comment by mthenw** [comment]
Hey @swasher, 

not sure how emperor works but is the error message looks the same for ` attach-daemon = frontail /home/vagrant/log/uwsgi-error.log`?

**Comment by swasher** [comment]
Yes, `attach-daemon = frontail /home/vagrant/log/uwsgi-error.log` got the same error message.

**Comment by mthenw** [comment]
@swasher not sure if you are still interested but, could you try running it on different node version. It looks like node's error.
