### ISSUE TITLE
--ui-highlight doens't find presets when installed globally on windows

### ISSUE THREAD

**Issue by HansHammel** [mthenw/frontail#62]
C:\somepath>frontail --ui-highlight 2016-01-29T10-46-56-server-access.log.2016-01-29
	module.js:339
	    throw err;
	    ^
	
	Error: Cannot find module 'C:\somepath\preset\default.json'
	    at Function.Module._resolveFilename (module.js:337:15)
	    at Function.Module._load (module.js:287:25)
	    at Module.require (module.js:366:17)
	    at require (module.js:385:17)
	    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\frontail\index.js:89:27)
	    at Module._compile (module.js:435:26)
	    at Object.Module._extensions..js (module.js:442:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:311:12)
	    at Module.require (module.js:366:17)

**Comment by mthenw** [comment]
Fixed. v2.2.1 released.
