### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jabrena** [mthenw/frontail#83]
Hi Using frontail, some times, I receive this error.

``` shell
buffer.js:975
  var val = this[offset + 1] | (this[offset] << 8);
                               ^
RangeError: Maximum call stack size exceeded
    at new Uint8Array (native)
    at Buffer.subarray (native)
    at Buffer.slice (buffer.js:822:23)
    at fromString (buffer.js:239:21)
    at Function.Buffer.from (buffer.js:131:12)
    at new Buffer (buffer.js:112:17)
```

**Comment by mthenw** [comment]
Thanks for reporting @jabrena!

Did you find a way to reproduce it?
